general {
    lock_cmd = omarchy-system-lock
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy-system-lock
    after_sleep_cmd = sleep 1 && omarchy-system-wake
    inhibit_sleep = 3
}

# Lock after 2 minutes, screen stays on
listener {
    timeout = 120
    on-timeout = OMARCHY_LOCK_ONLY=true omarchy-system-lock
    on-resume = omarchy-system-wake
}
