# tasks to complete before running roles
- hosts: localhost
  connection: local
  tags: always
  become: true
  pre_tasks:
    - name: Get System details
      debug: msg="{{ item }}"
      with_items:
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_distribution_major_version }}"

    - name: pre-run | update package cache
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Pop!_OS"]

# running roles for my personal workstation
- hosts: localhost
  connection: local
  tags: workstation
  become: true
  roles:
    - workstation

# after running everything
- hosts: localhost
  connection: local
  become: true
  tasks:
    - name: cleanup package cache
      tags: always
      apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution in ["Pop!_OS"]

    - name: autoremove orphan packages
      tags: always
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Pop!_OS"]
