---
- name: Install
  ansible.builtin.package:
    name:
      - git
    state: latest
  become: true

- name: Set diff.colorMoved
  community.general.git_config:
    name: diff.colorMoved
    scope: global
    value: zebra

- name: Set fetch.prune
  community.general.git_config:
    name: fetch.prune
    scope: global
    value: true

- name: Set init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Set pull.rebase
  community.general.git_config:
    name: pull.rebase
    scope: global
    value: true

- name: Set rebase.autoStash
  community.general.git_config:
    name: rebase.autoStash
    scope: global
    value: true

- name: Set rerere.enabled
  community.general.git_config:
    name: rerere.enabled
    scope: global
    value: true

- name: Set commit.gpgsign
  community.general.git_config:
    name: commit.gpgsign
    scope: global
    value: true

- name: Set user.signingkey
  community.general.git_config:
    name: user.signingkey
    scope: global
    value: "{{ git_user_signingkey }}"

- name: Set user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user_email }}"

- name: Set user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user_name }}"

