# Change the default Omarchy look'n'feel

general {
    border_size = 2
    col.active_border   = rgba(3d8f58ff)   # Racing Green
    col.inactive_border = rgba(1a2e2055)   # forest shadow muted
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 8
        passes = 3
        brightness = 0.85
        contrast = 0.9
        noise = 0.02
        new_optimizations = true
    }

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(0c181088)
    }
}
