# Change the default Omarchy look'n'feel

general {
    border_size = 2
    col.active_border   = rgba(1a1e1aff) rgba(2e322eff) 45deg   # carbon fibre
    col.inactive_border = rgba(0c100c44)                        # carbon quasi-invisible
}

decoration {
    rounding = 10

    blur {
        enabled = true
        size = 8
        passes = 3
        brightness = 0.85
        contrast = 0.9
        noise = 0.02
        new_optimizations = true
    }

    shadow {
        enabled = true
        range = 12
        render_power = 3
        color = rgba(0c181088)
    }
}

# blur behind waybar (matches terminal transparency)
layerrule = blur on, match:namespace waybar
