- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - at
      - colordiff
      - curl
      - htop
      - mc
      - neofetch
      - net-tools
      - nmap
      - rsync
      - screen
      - tmux
      - wget
      - whois
      - zsh
      - alacritty
      - neovim
      - python-setuptools
