# my default username
#
# todo
# - [x] directories
# - [] dotfiles
- name: users | neowindrunner | remove preinstalled clutter from home directory
  file:
    path: /home/neowindrunner/{{ item }}
    state: absent
  with_items:
    - examples.desktop
    - Desktop
    - Documents
    - Downloads
    - Music
    - Pictures
    - Public
    - Templates
    - Videos

- name: users | neowindrunner | create personal config directories
  tags: dotfiles, dotfiles-neowindrunner
  file:
    path: /home/neowindrunner/{{ item.dir }}
    state: directory
    owner: neowindrunnner
    group: neowindrunner
    mode: 0700
  with_items:
    - { dir: .config }
    - { dir: .local }
    - { dir: .local/share }
    - { dir: .local/share/applications }
    - { dir: bin }
    - { dir: desktop }
    - { dir: documents }
    - { dir: downloads }
    - { dir: projects }
    - { dir: bloomflow }
